events {}

http {
    upstream app_cluster {
        server app:8000;
    }

    server {
        listen 80;
        
        # Serve the HTML frontend
        location / {
            root /usr/share/nginx/html;
            index index.html;
        }

        # Route API requests to NestJS
        location /api/ {
            proxy_pass http://app_cluster/; 
        }
    }
}